# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: e4140303a4efbff7d18a494620187d1ef611a29dfc0c300f12a63306983022f6addf7079347de16575d904e2102b1f45b22f3b90af634a1839b0a90b721f0608

test:
  domain_name: example.com 
  secret_key_base: 4d31053f9df1c366bec6186eff78c8aa40257a74f0f9f6b4f92589659b47d449e89a838727e012fe1bf2f66a8888912c7d68dcfcd85d0e991dcc43f14dbbd5c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
